DROP FUNCTION pst.sprintf(fmt text, VARIADIC args "any");
DROP FUNCTION pst.sprintf(fmt text);
DROP FUNCTION pst.format(fmt text, VARIADIC args "any");
DROP FUNCTION pst.format(fmt text);
DROP FUNCTION pst.concat(VARIADIC args "any");
DROP FUNCTION pst.concat_ws(separator text, VARIADIC args "any");
DROP FUNCTION pst.concat_js(VARIADIC args "any");
DROP FUNCTION pst.concat_sql(VARIADIC args "any");
DROP FUNCTION pst.rvrs(str text);
DROP FUNCTION pst.left(str text, n int);
DROP FUNCTION pst.right(str text, n int);
DROP FUNCTION pst.chars_to_array(chars text);
DROP FUNCTION pst.next_day(d date, dow text);
DROP FUNCTION pst.last_day(d date);
DROP FUNCTION pst.counter(anyelement, int, bool);
DROP FUNCTION pst.diff_string(S text, T text);
DROP FUNCTION pst.lc_substring(S text, T text);
DROP FUNCTION pst.record_expand(record);
DROP FUNCTION pst.record_get_field(record, name text);
DROP FUNCTION pst.record_get_fields(record, VARIADIC names text[]);
DROP FUNCTION pst.record_set_fields(anyelement, VARIADIC params "any");
DROP FUNCTION pst.record_set_fields(anyelement, VARIADIC params text[]);
DROP FUNCTION pst.format_op(text, "any");
DROP TYPE pst.bitmapset CASCADE;